### ISSUE TITLE
proposiciones 

### ISSUE THREAD

**Issue by bibiana-m** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-bibiana-m#2]
[propociciones logicas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-bibiana-m/files/13221573/propociciones.logicas.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 22/25 (faltó objetivo)
FIGURAS 25/25
RESULTADO Y CONCLUCIÓN 15/25 (falta de conclución y resultados)
_______________________________________________________________________________
CALIFICACIÓN TOTAL 17.4/20

CALIFICADO POR ISAÍAS Y EQUIPO

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
